# Generated by Django 5.2.1 on 2025-05-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_training_time_trainingschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='trainingschedule',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='available_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='available_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='training_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.DeleteModel(
            name='TrainingSchedule',
        ),
    ]
