# Generated by Django 5.2.1 on 2025-05-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_shift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='training_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
