# Generated by Django 5.2.1 on 2025-05-21 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_training_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='training_time',
        ),
    ]
